apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tn-pvc-base-jetclass2
  namespace: cms-ml
spec:
  storageClassName: rook-cephfs  
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
