apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
  namespace: cms-ml
spec:
  containers:
  - name: shell
    image: ubuntu
    command: [ "sleep", "infinity" ]
    volumeMounts:
    - name: output-volume
      mountPath: /mnt/output
    tty: true
    stdin: true
  volumes:
  - name: output-volume
    persistentVolumeClaim:
      claimName: pvc  # your existing PVC name
  restartPolicy: Never
