apiVersion: batch/v1
kind: Job
metadata:
  name: tn-job-v5
  namespace: cms-ml           
spec:
  template:
    spec:
      containers:
      - name: tn-jetnet-part 
        image: pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime  
        command:
          - sh
          - -c
          - |
            cd /opt/repo/ParT_ParticleNet && \
            pip install --upgrade pip && \
            pip install numpy pandas matplotlib tqdm scikit-learn seaborn weaver-core jetnet tensorboard && \
            mkdir -p /mnt/output && \
            python main.py
        volumeMounts:
        - name: git-repo 
          mountPath: /opt/repo 
        - name: output-volume
          mountPath: /mnt/output  
        resources:
          limits:
            memory: "8Gi"
            cpu: "1"
            nvidia.com/gpu: "1"
          requests:
            memory: "8Gi"
            cpu: "1"
            nvidia.com/gpu: "1"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/cabbagecongee/Particle_Transformer_Fine_Tunning.git
          - /opt/repo
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: "600Mi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "1"
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: output-volume
        persistentVolumeClaim:
          claimName: pvc 
      restartPolicy: Never
  backoffLimit: 3
